Repository gvwilson/teachtogether.tech, pull requests merged in 2021-03, with the labels that each got.

#317 Revision of classroom.tex [es]
  es/classroom.tex
Labels: Spanish-Translation

#318 Second revisión of bib comments
  es/book.bib
Labels: Spanish-Translation

#333 Change start text in joining
  en/joining.tex
Labels: English

#331 First edition license
  es/license.tex
Labels: ‎Español

#332 firstEdition-CoC-Yani
  es/conduct.tex
Labels: ‎Español

#335 Meetings first edition Yani
  es/meetings.tex
Labels: ‎Español

#334 first edition joining
  es/joining.tex
Labels: ‎Español

#330 First edition - Why I teach - Yani
  es/finale.tex
Labels: ‎Español

#326 Segunda edición - classroom
  es/classroom.tex
Labels: ‎Español

#336 Uniform pair programming translation
  es/book.bib
Labels: ‎Español

#339 Temporal fix of Latex labels for the Spanish html & pdf versions
  tex/html-settings.tex
  tex/pdf-settings.tex
Labels: ‎Español

#342 Tiny edition - ConcepMapExample
  es/conceptmaps.tex
Labels: ‎Español

#340 exercises.tex 1st revision - Spanish version
  es/exercises.tex
Labels: ‎Español

#344 Add translator name - fix text
  es/traduccion.tex
  es/translation.tex
Labels: ‎Español

#345 models-seconEdition-Yani
  es/models.tex
Labels: ‎Español

#343 second edition to exercises - Yani
  es/exercises.tex
Labels: ‎Español

#349 Second edition for Memory
  es/memory.tex
Labels: ‎Español
